# Generated by Django 5.1.3 on 2024-12-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MisakaMikotoApp1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="misakamikoto",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="misakamikoto",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=254, unique=True
            ),
        ),
    ]
