# Generated by Django 5.1.3 on 2024-12-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MisakaMikotoApp1", "0002_alter_misakamikoto_age_alter_misakamikoto_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "email",
                    models.EmailField(
                        default="example@example.com", max_length=254, unique=True
                    ),
                ),
            ],
        ),
    ]
